// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/leaderboards": {
    params: {};
  };
  "/products/leaderboards/yearly/:year": {
    params: {
      "year": string;
    };
  };
  "/products/leaderboards/monthly/:year/:month": {
    params: {
      "year": string;
      "month": string;
    };
  };
  "/products/leaderboards/daily/:year/:month/:day": {
    params: {
      "year": string;
      "month": string;
      "day": string;
    };
  };
  "/products/leaderboards/weekly/:year/:week": {
    params: {
      "year": string;
      "week": string;
    };
  };
  "/products/leaderboards/:period": {
    params: {
      "period": string;
    };
  };
  "/products/categories": {
    params: {};
  };
  "/products/categories/:category": {
    params: {
      "category": string;
    };
  };
  "/products/search": {
    params: {};
  };
  "/products/submit": {
    params: {};
  };
  "/products/promote": {
    params: {};
  };
  "/products/promote/success": {
    params: {};
  };
  "/products/:productId": {
    params: {
      "productId": string;
    };
  };
  "/products/:productId/overview": {
    params: {
      "productId": string;
    };
  };
  "/products/:productId/reviews": {
    params: {
      "productId": string;
    };
  };
  "/products/:productId/visit": {
    params: {
      "productId": string;
    };
  };
  "/ideas": {
    params: {};
  };
  "/ideas/:ideaId": {
    params: {
      "ideaId": string;
    };
  };
  "/ideas/generate": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/jobs/:jobId": {
    params: {
      "jobId": string;
    };
  };
  "/jobs/submit": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/join": {
    params: {};
  };
  "/auth/otp/start": {
    params: {};
  };
  "/auth/otp/complete": {
    params: {};
  };
  "/auth/social/:provider/start": {
    params: {
      "provider": string;
    };
  };
  "/auth/social/:provider/complete": {
    params: {
      "provider": string;
    };
  };
  "/auth/logout": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/community/:postId": {
    params: {
      "postId": string;
    };
  };
  "/community/:postId/upvote": {
    params: {
      "postId": string;
    };
  };
  "/community/submit": {
    params: {};
  };
  "/teams": {
    params: {};
  };
  "/teams/:teamId": {
    params: {
      "teamId": string;
    };
  };
  "/teams/create": {
    params: {};
  };
  "/my/dashboard": {
    params: {};
  };
  "/my/dashboard/ideas": {
    params: {};
  };
  "/my/dashboard/products/:productId": {
    params: {
      "productId": string;
    };
  };
  "/my/messages": {
    params: {};
  };
  "/my/messages/:messageRoomId": {
    params: {
      "messageRoomId": string;
    };
  };
  "/my/profile": {
    params: {};
  };
  "/my/settings": {
    params: {};
  };
  "/my/notifications": {
    params: {};
  };
  "/my/notifications/:notificationId/see": {
    params: {
      "notificationId": string;
    };
  };
  "/users/:username": {
    params: {
      "username": string;
    };
  };
  "/users/:username/products": {
    params: {
      "username": string;
    };
  };
  "/users/:username/posts": {
    params: {
      "username": string;
    };
  };
  "/users/:username/messages": {
    params: {
      "username": string;
    };
  };
  "/users/:username/welcome": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/leaderboards" | "/products/leaderboards/yearly/:year" | "/products/leaderboards/monthly/:year/:month" | "/products/leaderboards/daily/:year/:month/:day" | "/products/leaderboards/weekly/:year/:week" | "/products/leaderboards/:period" | "/products/categories" | "/products/categories/:category" | "/products/search" | "/products/submit" | "/products/promote" | "/products/promote/success" | "/products/:productId" | "/products/:productId/overview" | "/products/:productId/reviews" | "/products/:productId/visit" | "/ideas" | "/ideas/:ideaId" | "/ideas/generate" | "/jobs" | "/jobs/:jobId" | "/jobs/submit" | "/auth/login" | "/auth/join" | "/auth/otp/start" | "/auth/otp/complete" | "/auth/social/:provider/start" | "/auth/social/:provider/complete" | "/auth/logout" | "/community" | "/community/:postId" | "/community/:postId/upvote" | "/community/submit" | "/teams" | "/teams/:teamId" | "/teams/create" | "/my/dashboard" | "/my/dashboard/ideas" | "/my/dashboard/products/:productId" | "/my/messages" | "/my/messages/:messageRoomId" | "/my/profile" | "/my/settings" | "/my/notifications" | "/my/notifications/:notificationId/see" | "/users/:username" | "/users/:username/products" | "/users/:username/posts" | "/users/:username/messages" | "/users/:username/welcome";
  };
  "common/pages/home-page.tsx": {
    id: "common/pages/home-page";
    page: "/";
  };
  "features/products/pages/products-page.tsx": {
    id: "features/products/pages/products-page";
    page: "/products";
  };
  "features/products/layouts/leaderboard-layout.tsx": {
    id: "features/products/layouts/leaderboard-layout";
    page: "/products/leaderboards" | "/products/leaderboards/yearly/:year" | "/products/leaderboards/monthly/:year/:month" | "/products/leaderboards/daily/:year/:month/:day" | "/products/leaderboards/weekly/:year/:week" | "/products/leaderboards/:period";
  };
  "features/products/pages/leaderboard-page.tsx": {
    id: "features/products/pages/leaderboard-page";
    page: "/products/leaderboards";
  };
  "features/products/pages/yearly-leaderboard-page.tsx": {
    id: "features/products/pages/yearly-leaderboard-page";
    page: "/products/leaderboards/yearly/:year";
  };
  "features/products/pages/monthly-leaderboard-page.tsx": {
    id: "features/products/pages/monthly-leaderboard-page";
    page: "/products/leaderboards/monthly/:year/:month";
  };
  "features/products/pages/daily-leaderboard-page.tsx": {
    id: "features/products/pages/daily-leaderboard-page";
    page: "/products/leaderboards/daily/:year/:month/:day";
  };
  "features/products/pages/weekly-leaderboard-page.tsx": {
    id: "features/products/pages/weekly-leaderboard-page";
    page: "/products/leaderboards/weekly/:year/:week";
  };
  "features/products/pages/leaderboards-redirection-page.tsx": {
    id: "features/products/pages/leaderboards-redirection-page";
    page: "/products/leaderboards/:period";
  };
  "features/products/pages/categories-page.tsx": {
    id: "features/products/pages/categories-page";
    page: "/products/categories";
  };
  "features/products/pages/category-page.tsx": {
    id: "features/products/pages/category-page";
    page: "/products/categories/:category";
  };
  "features/products/pages/search-page.tsx": {
    id: "features/products/pages/search-page";
    page: "/products/search";
  };
  "features/products/pages/submit-product-page.tsx": {
    id: "features/products/pages/submit-product-page";
    page: "/products/submit";
  };
  "features/products/pages/promote-page.tsx": {
    id: "features/products/pages/promote-page";
    page: "/products/promote";
  };
  "features/products/pages/promote-success-page.tsx": {
    id: "features/products/pages/promote-success-page";
    page: "/products/promote/success";
  };
  "features/products/pages/product-redirect-page.tsx": {
    id: "features/products/pages/product-redirect-page";
    page: "/products/:productId";
  };
  "features/products/layouts/product-overview-layout.tsx": {
    id: "features/products/layouts/product-overview-layout";
    page: "/products/:productId/overview" | "/products/:productId/reviews";
  };
  "features/products/pages/product-overview-page.tsx": {
    id: "features/products/pages/product-overview-page";
    page: "/products/:productId/overview";
  };
  "features/products/pages/product-reviews-page.tsx": {
    id: "features/products/pages/product-reviews-page";
    page: "/products/:productId/reviews";
  };
  "features/products/pages/product-visit-page.tsx": {
    id: "features/products/pages/product-visit-page";
    page: "/products/:productId/visit";
  };
  "features/ideas/pages/ideas-page.tsx": {
    id: "features/ideas/pages/ideas-page";
    page: "/ideas";
  };
  "features/ideas/pages/idea-page.tsx": {
    id: "features/ideas/pages/idea-page";
    page: "/ideas/:ideaId";
  };
  "features/ideas/pages/generate-idea-page.tsx": {
    id: "features/ideas/pages/generate-idea-page";
    page: "/ideas/generate";
  };
  "features/jobs/pages/jobs-page.tsx": {
    id: "features/jobs/pages/jobs-page";
    page: "/jobs";
  };
  "features/jobs/pages/job-page.tsx": {
    id: "features/jobs/pages/job-page";
    page: "/jobs/:jobId";
  };
  "features/jobs/pages/submit-job-page.tsx": {
    id: "features/jobs/pages/submit-job-page";
    page: "/jobs/submit";
  };
  "features/auth/layouts/auth-layout.tsx": {
    id: "features/auth/layouts/auth-layout";
    page: "/auth/login" | "/auth/join" | "/auth/otp/start" | "/auth/otp/complete" | "/auth/social/:provider/start" | "/auth/social/:provider/complete";
  };
  "features/auth/pages/login-page.tsx": {
    id: "features/auth/pages/login-page";
    page: "/auth/login";
  };
  "features/auth/pages/join-page.tsx": {
    id: "features/auth/pages/join-page";
    page: "/auth/join";
  };
  "features/auth/pages/otp-start-page.tsx": {
    id: "features/auth/pages/otp-start-page";
    page: "/auth/otp/start";
  };
  "features/auth/pages/otp-complete-page.tsx": {
    id: "features/auth/pages/otp-complete-page";
    page: "/auth/otp/complete";
  };
  "features/auth/pages/social-start-page.tsx": {
    id: "features/auth/pages/social-start-page";
    page: "/auth/social/:provider/start";
  };
  "features/auth/pages/social-complete-page.tsx": {
    id: "features/auth/pages/social-complete-page";
    page: "/auth/social/:provider/complete";
  };
  "features/auth/pages/logout-page.tsx": {
    id: "features/auth/pages/logout-page";
    page: "/auth/logout";
  };
  "features/community/pages/community-page.tsx": {
    id: "features/community/pages/community-page";
    page: "/community";
  };
  "features/community/pages/post-page.tsx": {
    id: "features/community/pages/post-page";
    page: "/community/:postId";
  };
  "features/community/pages/upvote-post-page.tsx": {
    id: "features/community/pages/upvote-post-page";
    page: "/community/:postId/upvote";
  };
  "features/community/pages/submit-post-page.tsx": {
    id: "features/community/pages/submit-post-page";
    page: "/community/submit";
  };
  "features/teams/pages/teams-page.tsx": {
    id: "features/teams/pages/teams-page";
    page: "/teams";
  };
  "features/teams/pages/team-page.tsx": {
    id: "features/teams/pages/team-page";
    page: "/teams/:teamId";
  };
  "features/teams/pages/submit-team-page.tsx": {
    id: "features/teams/pages/submit-team-page";
    page: "/teams/create";
  };
  "features/users/layouts/dashboard-layout.tsx": {
    id: "features/users/layouts/dashboard-layout";
    page: "/my/dashboard" | "/my/dashboard/ideas" | "/my/dashboard/products/:productId";
  };
  "features/users/pages/dashboard-page.tsx": {
    id: "features/users/pages/dashboard-page";
    page: "/my/dashboard";
  };
  "features/users/pages/dashboard-ideas-page.tsx": {
    id: "features/users/pages/dashboard-ideas-page";
    page: "/my/dashboard/ideas";
  };
  "features/users/pages/dashboard-product-page.tsx": {
    id: "features/users/pages/dashboard-product-page";
    page: "/my/dashboard/products/:productId";
  };
  "features/users/layouts/messages-layout.tsx": {
    id: "features/users/layouts/messages-layout";
    page: "/my/messages" | "/my/messages/:messageRoomId";
  };
  "features/users/pages/messages-page.tsx": {
    id: "features/users/pages/messages-page";
    page: "/my/messages";
  };
  "features/users/pages/message-page.tsx": {
    id: "features/users/pages/message-page";
    page: "/my/messages/:messageRoomId";
  };
  "features/users/pages/my-profile-page.tsx": {
    id: "features/users/pages/my-profile-page";
    page: "/my/profile";
  };
  "features/users/pages/settings-page.tsx": {
    id: "features/users/pages/settings-page";
    page: "/my/settings";
  };
  "features/users/pages/notifications-page.tsx": {
    id: "features/users/pages/notifications-page";
    page: "/my/notifications";
  };
  "features/users/pages/see-notification-page.tsx": {
    id: "features/users/pages/see-notification-page";
    page: "/my/notifications/:notificationId/see";
  };
  "features/users/layouts/profile-layout.tsx": {
    id: "features/users/layouts/profile-layout";
    page: "/users/:username" | "/users/:username/products" | "/users/:username/posts";
  };
  "features/users/pages/profile-page.tsx": {
    id: "features/users/pages/profile-page";
    page: "/users/:username";
  };
  "features/users/pages/profile-products-page.tsx": {
    id: "features/users/pages/profile-products-page";
    page: "/users/:username/products";
  };
  "features/users/pages/profile-posts-page.tsx": {
    id: "features/users/pages/profile-posts-page";
    page: "/users/:username/posts";
  };
  "features/users/pages/send-message-page.tsx": {
    id: "features/users/pages/send-message-page";
    page: "/users/:username/messages";
  };
  "features/users/pages/welcome-page.tsx": {
    id: "features/users/pages/welcome-page";
    page: "/users/:username/welcome";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "common/pages/home-page": typeof import("./app/common/pages/home-page.tsx");
  "features/products/pages/products-page": typeof import("./app/features/products/pages/products-page.tsx");
  "features/products/layouts/leaderboard-layout": typeof import("./app/features/products/layouts/leaderboard-layout.tsx");
  "features/products/pages/leaderboard-page": typeof import("./app/features/products/pages/leaderboard-page.tsx");
  "features/products/pages/yearly-leaderboard-page": typeof import("./app/features/products/pages/yearly-leaderboard-page.tsx");
  "features/products/pages/monthly-leaderboard-page": typeof import("./app/features/products/pages/monthly-leaderboard-page.tsx");
  "features/products/pages/daily-leaderboard-page": typeof import("./app/features/products/pages/daily-leaderboard-page.tsx");
  "features/products/pages/weekly-leaderboard-page": typeof import("./app/features/products/pages/weekly-leaderboard-page.tsx");
  "features/products/pages/leaderboards-redirection-page": typeof import("./app/features/products/pages/leaderboards-redirection-page.tsx");
  "features/products/pages/categories-page": typeof import("./app/features/products/pages/categories-page.tsx");
  "features/products/pages/category-page": typeof import("./app/features/products/pages/category-page.tsx");
  "features/products/pages/search-page": typeof import("./app/features/products/pages/search-page.tsx");
  "features/products/pages/submit-product-page": typeof import("./app/features/products/pages/submit-product-page.tsx");
  "features/products/pages/promote-page": typeof import("./app/features/products/pages/promote-page.tsx");
  "features/products/pages/promote-success-page": typeof import("./app/features/products/pages/promote-success-page.tsx");
  "features/products/pages/product-redirect-page": typeof import("./app/features/products/pages/product-redirect-page.tsx");
  "features/products/layouts/product-overview-layout": typeof import("./app/features/products/layouts/product-overview-layout.tsx");
  "features/products/pages/product-overview-page": typeof import("./app/features/products/pages/product-overview-page.tsx");
  "features/products/pages/product-reviews-page": typeof import("./app/features/products/pages/product-reviews-page.tsx");
  "features/products/pages/product-visit-page": typeof import("./app/features/products/pages/product-visit-page.tsx");
  "features/ideas/pages/ideas-page": typeof import("./app/features/ideas/pages/ideas-page.tsx");
  "features/ideas/pages/idea-page": typeof import("./app/features/ideas/pages/idea-page.tsx");
  "features/ideas/pages/generate-idea-page": typeof import("./app/features/ideas/pages/generate-idea-page.tsx");
  "features/jobs/pages/jobs-page": typeof import("./app/features/jobs/pages/jobs-page.tsx");
  "features/jobs/pages/job-page": typeof import("./app/features/jobs/pages/job-page.tsx");
  "features/jobs/pages/submit-job-page": typeof import("./app/features/jobs/pages/submit-job-page.tsx");
  "features/auth/layouts/auth-layout": typeof import("./app/features/auth/layouts/auth-layout.tsx");
  "features/auth/pages/login-page": typeof import("./app/features/auth/pages/login-page.tsx");
  "features/auth/pages/join-page": typeof import("./app/features/auth/pages/join-page.tsx");
  "features/auth/pages/otp-start-page": typeof import("./app/features/auth/pages/otp-start-page.tsx");
  "features/auth/pages/otp-complete-page": typeof import("./app/features/auth/pages/otp-complete-page.tsx");
  "features/auth/pages/social-start-page": typeof import("./app/features/auth/pages/social-start-page.tsx");
  "features/auth/pages/social-complete-page": typeof import("./app/features/auth/pages/social-complete-page.tsx");
  "features/auth/pages/logout-page": typeof import("./app/features/auth/pages/logout-page.tsx");
  "features/community/pages/community-page": typeof import("./app/features/community/pages/community-page.tsx");
  "features/community/pages/post-page": typeof import("./app/features/community/pages/post-page.tsx");
  "features/community/pages/upvote-post-page": typeof import("./app/features/community/pages/upvote-post-page.tsx");
  "features/community/pages/submit-post-page": typeof import("./app/features/community/pages/submit-post-page.tsx");
  "features/teams/pages/teams-page": typeof import("./app/features/teams/pages/teams-page.tsx");
  "features/teams/pages/team-page": typeof import("./app/features/teams/pages/team-page.tsx");
  "features/teams/pages/submit-team-page": typeof import("./app/features/teams/pages/submit-team-page.tsx");
  "features/users/layouts/dashboard-layout": typeof import("./app/features/users/layouts/dashboard-layout.tsx");
  "features/users/pages/dashboard-page": typeof import("./app/features/users/pages/dashboard-page.tsx");
  "features/users/pages/dashboard-ideas-page": typeof import("./app/features/users/pages/dashboard-ideas-page.tsx");
  "features/users/pages/dashboard-product-page": typeof import("./app/features/users/pages/dashboard-product-page.tsx");
  "features/users/layouts/messages-layout": typeof import("./app/features/users/layouts/messages-layout.tsx");
  "features/users/pages/messages-page": typeof import("./app/features/users/pages/messages-page.tsx");
  "features/users/pages/message-page": typeof import("./app/features/users/pages/message-page.tsx");
  "features/users/pages/my-profile-page": typeof import("./app/features/users/pages/my-profile-page.tsx");
  "features/users/pages/settings-page": typeof import("./app/features/users/pages/settings-page.tsx");
  "features/users/pages/notifications-page": typeof import("./app/features/users/pages/notifications-page.tsx");
  "features/users/pages/see-notification-page": typeof import("./app/features/users/pages/see-notification-page.tsx");
  "features/users/layouts/profile-layout": typeof import("./app/features/users/layouts/profile-layout.tsx");
  "features/users/pages/profile-page": typeof import("./app/features/users/pages/profile-page.tsx");
  "features/users/pages/profile-products-page": typeof import("./app/features/users/pages/profile-products-page.tsx");
  "features/users/pages/profile-posts-page": typeof import("./app/features/users/pages/profile-posts-page.tsx");
  "features/users/pages/send-message-page": typeof import("./app/features/users/pages/send-message-page.tsx");
  "features/users/pages/welcome-page": typeof import("./app/features/users/pages/welcome-page.tsx");
};